
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: manyou_exam_development



test:
  <<: *default
  database: manyou_exam_test


production:
  <<: *default
  database: manyou_exam_production
  username: manyou_exam
  password: <%= ENV['MANYOU_EXAM_DATABASE_PASSWORD'] %>
